// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    // The original SQLite history remains in prisma/migrations for ETL/source replay only.
    path: "prisma/migrations-mysql",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
