ALTER TABLE "User" ADD COLUMN "membershipTier" TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "User" ADD COLUMN "vipStartedAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "vipPaidUntil" DATETIME;
ALTER TABLE "User" ADD COLUMN "vipLastReminderSentAt" DATETIME;
